version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/back"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"
